### ISSUE TITLE
咨询代码问题

### ISSUE THREAD

**Issue by Keep-lucky** [WENGSYX/GlobalSpan#1]
代码作者您好，我阅读了您的论文与代码，发现在model文件代码中，如图中的Textual Projection模块并没有表现出来，请问这部分缺失，会对模型的表现存在什么影响嘛？ 叨扰到您，敬请见谅。
![583d723e1382c0a513071b0f697035b](https://github.com/WENGSYX/CCGS/assets/71928923/f3712ade-cfe5-48db-be10-c74a460f715e)
7b6-de3a7882e2e0)

![16b383c919cdb07912f6f3a2e798d66](https://github.com/WENGSYX/CCGS/assets/71928923/97f58ec1-5975-4393-aa6d-50d3ed1a797b)

**Comment by WENGSYX** [comment]
您好！非常感谢您阅读我们的论文和代码。关于您提到的Textual Projection模块，请允许我为您解释一下。

在我们最初的设计中，我们确实使用了与PLM相同隐藏层维度的线性层作为Textual Projection。然而，在后期实验和分析过程中，我们发现这个线性层对模型的性能影响不大。基于这一发现，我们决定将PLM与Textual Projection视为一个整体，即使用类似于BERT的语言模型来进行语言部分的特征提取和投影。

因此，尽管Textual Projection模块在代码中没有明确体现，但实际上这个功能已经在PLM中实现。所以请您放心，模型的性能不会受到这个变化的影响。

再次感谢您的关注和反馈，如果您有任何其他疑问，或者需要更多关于我们论文和代码的信息，请随时联系我们。祝您一切顺利！

**Comment by Keep-lucky** [comment]
> 您好！非常感谢您阅读我们的论文和代码。关于您提到的Textual Projection模块，请允许我为您解释一下。
> 
> 在我们最初的设计中，我们确实使用了与PLM相同隐藏层维度的线性层作为Textual Projection。然而，在后期实验和分析过程中，我们发现这个线性层对模型的性能影响不大。基于这一发现，我们决定将PLM与Textual Projection视为一个整体，即使用类似于BERT的语言模型来进行语言部分的特征提取和投影。
> 
> 因此，尽管Textual Projection模块在代码中没有明确体现，但实际上这个功能已经在PLM中实现。所以请您放心，模型的性能不会受到这个变化的影响。
> 
> 再次感谢您的关注和反馈，如果您有任何其他疑问，或者需要更多关于我们论文和代码的信息，请随时联系我们。祝您一切顺利！

非常感谢您的回答，祝您生活愉快！
